# .github/workflows/code-review.yml
name: Code Review
on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 必须设置才能获取变更文件

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 安装依赖
        run: npm ci

      - name: 执行代码审查
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: npx tsx src/cli.mts

      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: code-review-results
          path: review-results.json